// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfaakagaRrrAUTcd5NYUUxEsYWwHLa0l8',
    appId: '1:1064735442499:web:312127ebd9a828511a36f6',
    messagingSenderId: '1064735442499',
    projectId: 'fashion-shop-v1',
    authDomain: 'fashion-shop-v1.firebaseapp.com',
    storageBucket: 'fashion-shop-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfHNmI9kM-M3DEBVFsqu-0ZBbiq2iJmHY',
    appId: '1:1064735442499:android:5658b764e8ca84c91a36f6',
    messagingSenderId: '1064735442499',
    projectId: 'fashion-shop-v1',
    storageBucket: 'fashion-shop-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp8ZAzy9FQYjxPUkXZjuzTmxEOs92yFkA',
    appId: '1:1064735442499:ios:9202e2b0b6e4387c1a36f6',
    messagingSenderId: '1064735442499',
    projectId: 'fashion-shop-v1',
    storageBucket: 'fashion-shop-v1.firebasestorage.app',
    iosBundleId: 'com.example.flutterProviderShoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp8ZAzy9FQYjxPUkXZjuzTmxEOs92yFkA',
    appId: '1:1064735442499:ios:9202e2b0b6e4387c1a36f6',
    messagingSenderId: '1064735442499',
    projectId: 'fashion-shop-v1',
    storageBucket: 'fashion-shop-v1.firebasestorage.app',
    iosBundleId: 'com.example.flutterProviderShoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfaakagaRrrAUTcd5NYUUxEsYWwHLa0l8',
    appId: '1:1064735442499:web:28ce72515120e9b91a36f6',
    messagingSenderId: '1064735442499',
    projectId: 'fashion-shop-v1',
    authDomain: 'fashion-shop-v1.firebaseapp.com',
    storageBucket: 'fashion-shop-v1.firebasestorage.app',
  );

}